
public class StringArrays {
	public static String[] programmingTerms = new String[] {
		    "Java",
		    "Python",
		    "C++",
		    "C#",
		    "JavaScript",
		    "Ruby",
		    "Swift",
		    "Go",
		    "Kotlin",
		    "SQL",
		    "HTML",
		    "CSS",
		    "PHP",
		    "R",
		    "Scala",
		    "TypeScript",
		    "Object-Oriented Programming",
		    "Functional Programming",
		    "Agile Development",
		    "Test-Driven Development",
		    "Continuous Integration",
		    "Continuous Deployment",
		    "Software Development Life Cycle",
		    "Debugging",
		    "Compiler",
		    "Interpreter",
		    "Virtual Machine",
		    "Garbage Collection",
		    "API",
		    "SDK",
		    "IDE",
		    "Operating System",
		    "Command Line Interface",
		    "Database",
		    "Object Relational Mapping",
		    "Data Structures",
		    "Algorithms",
		    "Encryption",
		    "Decryption",
		    "Syntax",
		    "Semantics",
		    "Git",
		    "Source Control Management",
		    "Version Control",
		    "Bug Tracking",
		    "Issue Tracking",
		    "Backend Development",
		    "Frontend Development",
		    "Full Stack Development",
		    "Mobile Development",
		    "Game Development",
		    "Artificial Intelligence",
		    "Machine Learning",
		    "Neural Network",
		    "Deep Learning",
		    "Computer Vision",
		    "Natural Language Processing",
		    "Blockchain",
		    "Smart Contracts",
		    "Ethereum",
		    "Bitcoin",
		    "Cryptocurrency",
		    "Distributed Systems",
		    "Load Balancing",
		    "Serverless Computing",
		    "Cloud Computing",
		    "DevOps",
		    "Containerization",
		    "Continuous Testing",
		    "Continuous Monitoring",
		    "Microservices",
		    "Web Services",
		    "Restful API",
		    "SOAP API",
		    "NoSQL",
		    "Big Data",
		    "Data Analytics",
		    "Data Science",
		    "Data Mining",
		    "Data Visualization",
		    "User Experience",
		    "User Interface",
		    "Accessibility",
		    "Cybersecurity",
		    "Penetration Testing",
		    "White Hat Hacking",
		    "Grey Hat Hacking",
		    "Black Hat Hacking",
		};
	public static String[] requests = new String[] {
			  "What is Java?",
			  "How to create a chatbot in Java?",
			  "How do I set classpath in Eclipse?",
			  "What is NLPcore?",
			  "How to build a spell checker in Java?",
			  "What is a neural network?",
			  "What is OpenAI?",
			  "What is the difference between NLP and NLU?",
			  "What is a blockchain?",
			  "What is a smart contract?",
			  "How do I add a directory to PATH environment variable?",
			  "How do I create an array in Java?",
			  "What is the difference between an array and an ArrayList in Java?",
			  "What is a method in Java?",
			  "What is a class in Java?",
			  "What is an object in Java?",
			  "What is inheritance in Java?",
			  "What is polymorphism in Java?",
			  "What is an interface in Java?",
			  "What is a package in Java?",
			  "What is a JAR file in Java?",
			  "What is a JRE in Java?",
			  "What is a JDK in Java?",
			  "What is a servlet in Java?",
			  "What is a JSP in Java?",
			  "What is a Java Bean?",
			  "What is a JPA in Java?",
			  "What is a Hibernate in Java?",
			  "What is a REST API?",
			  "What is a SOAP API?",
			  "What is an API gateway?",
			  "What is a microservice?",
			  "What is a containerization?",
			  "What is a virtualization?",
			  "What is a cloud computing?",
			  "What is a serverless computing?",
			  "What is a Load Balancer?",
			  "What is an SSL certificate?",
			  "What is a DNS?",
			  "What is a firewall?",
			  "What is a VPN?",
			  "What is a VPS?",
			  "What is a Dedicated Server?",
			  "What is a cluster?",
			  "What is a node?",
			  "What is a database?",
			  "What is a SQL database?",
			  "What is a NoSQL database?",
			  "What is a data warehouse?",
			  "What is big data?",
			  "What is data mining?",
			  "What is a data scientist?",
			  "What is a machine learning?",
			  "What is a deep learning?",
			  "What is a neural network?",
			  "What is a TensorFlow?",
			  "What is a Keras?",
			  "What is a PyTorch?",
			  "What is a Caffe?",
			  "What is a Theano?",
			  "What is a OpenCV?",
			  "What is a scikit-learn?",
			  "What is a NumPy?",
			  "What is a Pandas?",
			  "What is a Matplotlib?",
			  "What is a Seaborn?",
			  "What is a Plotly?",
			  "What is a Bokeh?",
			  "What is a Tkinter?",
			  "What is a Pygame?",
			  "What is a PyQt?",
			  "What is a Kivy?",
			  "What is a wxPython?",
			  "What is a PyGTK?",
			  "What is a Pyglet?",
			  "How do I integrate PayPal into my website?",
			  "What is the difference between Stack and Queue?",
			  "What is the purpose of JUnit in Java?",
			  "How to make a REST API in Java?",
			  "What is the use of a Set in Java?",
			  "How to handle exceptions in Java?",
			  "What is the difference between interface and abstract class?",
			  "How do I send an email using Java?",
			  "What is the purpose of serialization in Java?",
			  "How do I connect to a database in Java?"
	};
	public static String[] basic = {
			  "Can we play video games?",
			  "What's for dinner?",
			  "I don't want to go to school today.",
			  "Can I have a snack?",
			  "I don't like vegetables.",
			  "Can we go to the park?",
			  "Do I have any homework?",
			  "Can I sleepover at my friend's house?",
			  "What are we doing today?",
			  "Can I watch TV?",
			  "I don't like my teacher.",
			  "Can I have a sleepover?",
			  "I'm bored.",
			  "I want to play outside.",
			  "Can I have a playdate?",
			  "I don't want to brush my teeth.",
			  "Can I have a soda?",
			  "What's for lunch?",
			  "Can we go to the pool?",
			  "Can I go to the bathroom?",
			  "I don't like math.",
			  "Can we have ice cream?",
			  "Can I play with my friends?",
			  "Do I have any tests tomorrow?",
			  "Can we go to the movies?",
			  "Can I have candy?",
			  "I don't like my clothes.",
			  "Can we go to the arcade?",
			  "Can I play on my tablet?",
			  "What's for breakfast?",
			  "Can we go bike riding?",
			  "I don't like my hair.",
			  "Can I have a popsicle?",
			  "I want to play with my toys.",
			  "Can we go to the museum?",
			  "Can I have a juice box?",
			  "Can I play on my computer?",
			  "I don't like science.",
			  "Can we go bowling?",
			  "What's for lunch tomorrow?",
			  "Can I have a milkshake?",
			  "Can we go to the zoo?",
			  "I want to play with my legos.",
			  "Can I have a hot dog?",
			  "Can I play with my dolls?",
			  "Can we go to the amusement park?",
			  "I don't like history.",
			  "Can I have a smoothie?",
			  "Can we go to the beach?",
			  "Can I play with my action figures?",
			  "Can I have a cheeseburger?",
			  "Can we go to the water park?",
			  "I want to play with my blocks.",
			  "Can I have a slushie?",
			  "Can I play with my games?",
			  "Can we go to the aquarium?",
			  "I don't like reading.",
			  "Can I have a cotton candy?",
			  "Can I play with my coloring books?",
			  "Can we go to the science center?",
			  "Can I have a snow cone?",
			  "Can I play with my play-doh?",
			  "Can we go to the library?",
			  "I don't like writing.",
			  "Can I have a nachos?",
			  "Can I play with my stickers?",
			  "Can we go to the candy store?",
			  "Can I have a pretzel?",
			  "Can I play with my puzzles?",
			  "Can we go to the toy store?",
			  "I don't like gym.",
			  "Can I have a hot chocolate?",
			  "Can I play with my board games?",
	};
	public static String[] search = {
		    "how to boil eggs",
		    "best pizza near me",
		    "how to tie a tie",
		    "best laptop for programming",
		    "how to lose weight fast",
		    "best restaurants in New York",
		    "how to start a garden",
		    "best VPN service",
		    "how to train for a marathon",
		    "best places to travel in 2021",
		    "how to make lasagna",
		    "best smartphones 2021",
		    "how to improve public speaking skills",
		    "best romantic movies",
		    "how to make coffee",
		    "best home gym equipment",
		    "how to learn a new language",
		    "best online courses",
		    "how to make pancakes",
		    "best sports cars",
		    "how to start investing",
		    "best books for entrepreneurs",
		    "how to make chicken alfredo",
		    "best horror movies",
		    "how to reduce stress",
		    "best workout music",
		    "how to make sushi",
		    "best healthy recipes",
		    "how to improve memory",
		    "best self help books",
		    "how to make a budget",
		    "best budget laptops",
		    "how to fix a flat tire",
		    "best travel deals",
		    "how to write a resume",
		    "best travel credit card",
		    "how to make a smoothie",
		    "best beach vacations",
		    "how to negotiate salary",
		    "best budget smartphones",
		    "how to meditate",
		    "best romantic comedies",
		    "how to get rid of acne",
		    "best gaming laptops",
		    "how to find a job",
		    "best home security systems",
		    "how to make fried rice",
		    "best weight loss supplements",
		    "how to make a fire pit"
		};

}
